/* WorkflowPanelWidget.cpp
   Refactored to use resources/WorkflowPanelWidget.ui (uic-generated header).
   Do not create a manual ui_WorkflowPanelWidget.h here; the build system will
   generate it via uic. This file adopts the UI-created widgets into the
   existing member variables and preserves original behavior.
*/

#include "WorkflowPanelWidget.h"
#include "CollapsibleGroupBox.h"
#include "CropController.h"
#include "ui_WorkflowPanelWidget.h" // generated by uic
#include "WindowLevelController.h"  // <-- ensure controller type is known
#include "LightboxWidget.h" // <-- add include

#include <memory>
#include <QLayout>
#include <QDebug>
#include <QCoreApplication>
#include <QVariant>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QLabel>
#include <QFrame>
#include <QScrollArea>
#include <QResizeEvent>

WorkflowPanelWidget::WorkflowPanelWidget(QWidget* parent)
	: QWidget(parent)
{
	// Use uic-generated UI to build widgets/layouts.
	std::unique_ptr<Ui::WorkflowPanelWidget> ui(new Ui::WorkflowPanelWidget());
	ui->setupUi(this);

	// Adopt UI widgets into existing member variables so rest of the class can
	// continue using the same names and logic.
	m_scrollArea = ui->scrollArea;
	m_scrollContent = ui->scrollContent;
	m_rootLayout = ui->rootLayout;

	// Load group
	m_grpLoad = ui->grpLoad;
	m_btnLoadImage = ui->btnLoadImage;
	// keep legacy container pointer null (UI owns the group content)
	m_loadContainer = nullptr;
	if (m_btnLoadImage) {
		connect(m_btnLoadImage, &QPushButton::clicked, this, &WorkflowPanelWidget::onLoadImageClicked);
	}

	// Cropping group: the .ui places a native CropController instance
	m_grpCropping = ui->grpCropping;
	// UI provides a CropController named cropController; use it as the custom widget
	m_customCroppingWidget = ui->cropController;
	// There are no separate define/apply/save buttons in the UI; ensure legacy pointers are null
	m_croppingContainer = nullptr;
	m_btnDefineCrop = nullptr;
	m_btnApplyCrop = nullptr;
	m_btnSaveCropped = nullptr;
	m_btnLoadCropped = nullptr;

	// Wire CropController signals to existing slots/signals
	if (auto* crop = qobject_cast<CropController*>(m_customCroppingWidget.data())) {
		connect(crop, &CropController::defineCropToggled, this, [this](bool) { emit defineCropRequested(); });
		connect(crop, &CropController::applyCropRequested, this, &WorkflowPanelWidget::onApplyCropClicked);
		connect(crop, &CropController::saveCroppedRequested, this, &WorkflowPanelWidget::onSaveCroppedClicked);
		// Forward croppingRegionChanged so external owners can react in real time.
		connect(crop, &CropController::croppingRegionChanged,
				this, &WorkflowPanelWidget::croppingRegionChanged, Qt::UniqueConnection);
	}

	// Fiducials group
	m_grpFiducials = ui->grpFiducials;
	m_fiducialsContainer = nullptr;
	m_btnPlaceFiducials = ui->btnPlaceFiducials;
	if (m_btnPlaceFiducials) connect(m_btnPlaceFiducials, &QPushButton::clicked, this, &WorkflowPanelWidget::onPlaceFiducialsClicked);

	// Rotation group
	m_grpRotation = ui->grpRotation;
	m_rotationContainer = nullptr;
	m_btnStartInteractiveRotation = ui->btnStartInteractiveRotation;
	m_btnApplyRotation = ui->btnApplyRotation;
	if (m_btnStartInteractiveRotation) connect(m_btnStartInteractiveRotation, &QPushButton::clicked, this, &WorkflowPanelWidget::onStartInteractiveRotationClicked);
	if (m_btnApplyRotation) connect(m_btnApplyRotation, &QPushButton::clicked, this, &WorkflowPanelWidget::onApplyRotationClicked);

	// Segmentation group
	m_grpSegmentation = ui->grpSegmentation;
	m_segmentationContainer = nullptr;
	m_btnComputeThreshold = ui->btnComputeThreshold;
	m_btnPreviewThreshold = ui->btnPreviewThreshold;
	m_btnRunSegmentation = ui->btnRunSegmentation;
	m_btnSaveSegment = ui->btnSaveSegment;
	if (m_btnComputeThreshold) connect(m_btnComputeThreshold, &QPushButton::clicked, this, &WorkflowPanelWidget::onComputeThresholdClicked);
	if (m_btnPreviewThreshold) connect(m_btnPreviewThreshold, &QPushButton::clicked, this, &WorkflowPanelWidget::onPreviewThresholdClicked);
	if (m_btnRunSegmentation) connect(m_btnRunSegmentation, &QPushButton::clicked, this, &WorkflowPanelWidget::onRunSegmentationClicked);
	if (m_btnSaveSegment) connect(m_btnSaveSegment, &QPushButton::clicked, this, &WorkflowPanelWidget::onSaveSegmentClicked);

	// Appearance group
	m_grpAppearance = ui->grpAppearance;
	m_appearanceContainer = nullptr;

	// If the UI placed a WindowLevelController instance, adopt it now
	if (ui->windowLevelController) {
		// Remember pointer; UI already parented it into the grpAppearance container
		m_windowLevelController = ui->windowLevelController;
		m_customAppearanceWidget = ui->windowLevelController;

		// Forward committed adjustments as a panel-level hint/signal
		connect(m_windowLevelController, &WindowLevelController::windowLevelCommitted,
				this, &WorkflowPanelWidget::windowLevelAdjusted, Qt::UniqueConnection);
	}

	// Ensure groups adopt same size/policy behavior as original implementation.
	adjustGroupWidths();

	// Add stretch to push groups to the top (UI's root layout already contains items; add the stretch here).
	if (m_rootLayout) m_rootLayout->addStretch(1);
}

// The rest of the implementation is unchanged and continues to operate on the
// member variables that were bound above.

void WorkflowPanelWidget::adjustGroupWidths()
{
	if (!m_scrollArea || !m_scrollContent) return;

	// Available width inside the scroll area's viewport
	int avail = m_scrollArea->viewport()->width();
	// leave some padding for group margins/arrow/title
	const int padding = 24;
	int target = qMax(220, avail - padding);

	// Apply maximum width so layout will reflow and never require a horizontal scrollbar.
	const QList<QWidget*> groups = {
		m_grpLoad, m_grpCropping, m_grpFiducials,
		m_grpRotation, m_grpSegmentation, m_grpAppearance
	};
	for (QWidget* g : groups) {
		if (!g) continue;
		g->setMaximumWidth(target);
		g->setMinimumWidth(0); // do not force a large minimum width
		// ensure child widgets can expand horizontally
		// IMPORTANT: use Preferred vertical policy (not Minimum) so the group's
		// height can grow to accommodate its content when expanded.
		g->setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
	}

	// Allow content widget to shrink/grow with the viewport
	m_scrollContent->setMinimumWidth(0);
	m_scrollContent->setMaximumWidth(target);
}

void WorkflowPanelWidget::resizeEvent(QResizeEvent* event)
{
	QWidget::resizeEvent(event);
	// Recompute group widths to fit the new viewport size
	adjustGroupWidths();
}

CollapsibleGroupBox* WorkflowPanelWidget::makeGroup(const QString& title)
{
	// Compatibility path: still allow dynamic creation of groups.
	QWidget* parentForGroup = m_scrollContent ? m_scrollContent : this;
	auto* g = new CollapsibleGroupBox(title, parentForGroup);
	g->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Minimum);
	return g;
}

QLabel* WorkflowPanelWidget::makePlaceholderLabel(const QString& text)
{
	auto* l = new QLabel(text, this);
	l->setWordWrap(true);
	l->setFrameStyle(QFrame::StyledPanel | QFrame::Plain);
	l->setContentsMargins(4, 4, 4, 4);
	return l;
}

void WorkflowPanelWidget::insertVolumeCroppingWidget(QWidget* widget)
{
	if (!widget) return;
	// clear existing content
	if (m_customCroppingWidget) {
		m_customCroppingWidget->setParent(nullptr);
	}
	if (m_grpCropping) {
		// Use group's setter to install the widget if available
		m_grpCropping->setContentWidget(widget);
	}
	widget->setParent(m_grpCropping);
	m_customCroppingWidget = widget;
}

void WorkflowPanelWidget::insertFiducialsWidget(QWidget* widget)
{
	if (!widget) return;
	if (m_customFiducialsWidget) m_customFiducialsWidget->setParent(nullptr);
	widget->setParent(m_fiducialsContainer ? m_fiducialsContainer : m_grpFiducials);
	auto* lay = qobject_cast<QVBoxLayout*>((m_fiducialsContainer ? m_fiducialsContainer->layout() : nullptr));
	if (lay) lay->insertWidget(0, widget);
	m_customFiducialsWidget = widget;
}

void WorkflowPanelWidget::insertVolumeRotationWidget(QWidget* widget)
{
	if (!widget) return;
	if (m_customRotationWidget) m_customRotationWidget->setParent(nullptr);
	widget->setParent(m_rotationContainer ? m_rotationContainer : m_grpRotation);
	auto* lay = qobject_cast<QVBoxLayout*>((m_rotationContainer ? m_rotationContainer->layout() : nullptr));
	if (lay) lay->insertWidget(0, widget);
	m_customRotationWidget = widget;
}

void WorkflowPanelWidget::insertSegmentationWidget(QWidget* widget)
{
	if (!widget) return;
	if (m_customSegmentationWidget) m_customSegmentationWidget->setParent(nullptr);
	widget->setParent(m_segmentationContainer ? m_segmentationContainer : m_grpSegmentation);
	auto* lay = qobject_cast<QVBoxLayout*>((m_segmentationContainer ? m_segmentationContainer->layout() : nullptr));
	if (lay) lay->insertWidget(0, widget);
	m_customSegmentationWidget = widget;
}

void WorkflowPanelWidget::insertAppearanceWidget(QWidget* widget)
{
	if (!widget) return;
	if (m_customAppearanceWidget) m_customAppearanceWidget->setParent(nullptr);
	widget->setParent(m_appearanceContainer ? m_appearanceContainer : m_grpAppearance);
	auto* lay = qobject_cast<QVBoxLayout*>((m_appearanceContainer ? m_appearanceContainer->layout() : nullptr));
	if (lay) lay->insertWidget(0, widget);
	m_customAppearanceWidget = widget;
}

void WorkflowPanelWidget::setCroppingEnabled(bool on)
{
	if (!m_grpCropping) return;

	// If UI provided a CropController, forward enable/disable via that widget.
	if (auto* c = qobject_cast<CropController*>(m_customCroppingWidget.data())) {
		c->onExternalCroppingChanged(on);
	}

	// Keep legacy button pointers in sync if present
	if (m_btnDefineCrop) m_btnDefineCrop->setEnabled(on);
	if (m_btnApplyCrop) m_btnApplyCrop->setEnabled(on);
	if (m_btnLoadCropped) m_btnLoadCropped->setEnabled(on);
	if (m_btnSaveCropped) m_btnSaveCropped->setEnabled(on);

	// Enable/disable the cropping group itself and expand when enabled
	m_grpCropping->setEnabled(on);
	m_grpCropping->setCollapsed(!on);
}

bool WorkflowPanelWidget::isCroppingEnabled() const
{
	return m_grpCropping ? m_grpCropping->isEnabled() : false;
}

void WorkflowPanelWidget::setRotationEnabled(bool on)
{
	if (!m_grpRotation) return;

	// Keep controls enabled/disabled for accessibility
	if (m_btnStartInteractiveRotation) m_btnStartInteractiveRotation->setEnabled(on);
	if (m_btnApplyRotation) m_btnApplyRotation->setEnabled(on);

	m_grpRotation->setEnabled(on);
	m_grpRotation->setCollapsed(!on);
}

bool WorkflowPanelWidget::isRotationEnabled() const
{
	return m_grpRotation ? m_grpRotation->isEnabled() : false;
}

void WorkflowPanelWidget::setSegmentationEnabled(bool on)
{
	if (!m_grpSegmentation) return;

	// Keep controls enabled/disabled for accessibility
	if (m_btnComputeThreshold) m_btnComputeThreshold->setEnabled(on);
	if (m_btnPreviewThreshold) m_btnPreviewThreshold->setEnabled(on);
	if (m_btnRunSegmentation) m_btnRunSegmentation->setEnabled(on);
	if (m_btnSaveSegment) m_btnSaveSegment->setEnabled(on);

	m_grpSegmentation->setEnabled(on);
	m_grpSegmentation->setCollapsed(!on);
}

bool WorkflowPanelWidget::isSegmentationEnabled() const
{
	return m_grpSegmentation ? m_grpSegmentation->isEnabled() : false;
}

void WorkflowPanelWidget::setFiducialsEnabled(bool on)
{
	if (!m_grpFiducials) return;

	// Keep controls enabled/disabled for accessibility
	if (m_btnPlaceFiducials) m_btnPlaceFiducials->setEnabled(on);

	m_grpFiducials->setEnabled(on);
	m_grpFiducials->setCollapsed(!on);
}

bool WorkflowPanelWidget::isFiducialsEnabled() const
{
	return m_grpFiducials ? m_grpFiducials->isEnabled() : false;
}

void WorkflowPanelWidget::setAppearanceEnabled(bool /*on*/)
{
	// Appearance controls are independent of processing pipeline.
	// Always keep appearance group enabled and expanded so users can change
	// visible properties (window/level, etc.) for any loaded image.
	if (m_grpAppearance) {
		m_grpAppearance->setEnabled(true);
		m_grpAppearance->setCollapsed(false); // ensure open
	}
}

bool WorkflowPanelWidget::isAppearanceEnabled() const
{
	// Appearance group is always available when created.
	return m_grpAppearance ? m_grpAppearance->isEnabled() : false;
}

// -----------------------------------------------------------------------------
// Missing slot definitions - emit the corresponding signals
// -----------------------------------------------------------------------------
void WorkflowPanelWidget::onLoadImageClicked()
{
	emit loadImageRequested();
}

void WorkflowPanelWidget::onDefineCropClicked()
{
	emit defineCropRequested();
}

void WorkflowPanelWidget::onApplyCropClicked()
{
	emit applyCropRequested();
}

void WorkflowPanelWidget::onLoadCroppedClicked()
{
	emit loadCroppedRequested();
}

void WorkflowPanelWidget::onPlaceFiducialsClicked()
{
	emit placeFiducialsRequested();
}

void WorkflowPanelWidget::onStartInteractiveRotationClicked()
{
	emit startInteractiveRotationRequested();
}

void WorkflowPanelWidget::onApplyRotationClicked()
{
	emit applyRotationRequested();
}

void WorkflowPanelWidget::onComputeThresholdClicked()
{
	emit computeThresholdRequested();
}

void WorkflowPanelWidget::onPreviewThresholdClicked()
{
	emit previewThresholdRequested();
}

void WorkflowPanelWidget::onRunSegmentationClicked()
{
	emit runSegmentationRequested();
}

void WorkflowPanelWidget::onSaveSegmentClicked()
{
	emit saveSegmentRequested();
}

// new: save cropped slot
void WorkflowPanelWidget::onSaveCroppedClicked()
{
	emit saveCroppedRequested();
}

// new fine-grained control implementations
void WorkflowPanelWidget::setDefineCropEnabled(bool on)
{
	if (m_btnDefineCrop) m_btnDefineCrop->setEnabled(on);
}

void WorkflowPanelWidget::setApplyCropEnabled(bool on)
{
	if (m_btnApplyCrop) m_btnApplyCrop->setEnabled(on);
}

void WorkflowPanelWidget::setSaveCroppedEnabled(bool on)
{
	if (m_btnSaveCropped) m_btnSaveCropped->setEnabled(on);
}

// New: centralized expand/collapse policy driven by state machine state.
// NOTE: this only updates the visual collapsed/expanded state of the group boxes.
// Enabling/disabling of controls remains the responsibility of the caller (MainWindow).
void WorkflowPanelWidget::applyState(ImageProcessingStateMachine::State s, bool imagePresent)
{
	bool enableCropping = false;
	bool enableRotation = false;
	bool enableSegmentation = false;
	bool enableFiducials = false;

	// Default collapse policy flag for which group should be expanded
	enum class ExpandTarget { None, Cropping, Rotation, Fiducials, Segmentation } expand = ExpandTarget::None;

	switch (s) {
		case ImageProcessingStateMachine::Idle:
		case ImageProcessingStateMachine::Completed:
		case ImageProcessingStateMachine::ErrorState:
		// When idle/completed/error: workflow groups become available only when an image is present.
		enableCropping = imagePresent;
		enableRotation = imagePresent;
		enableSegmentation = imagePresent;
		enableFiducials = imagePresent;

		// Expand cropping by default when image present; keep appearance accessible as well.
		expand = imagePresent ? ExpandTarget::Cropping : ExpandTarget::None;
		break;

		case ImageProcessingStateMachine::LoadingImage:
		// While loading everything should be disabled and collapsed.
		// keep all flags false
		expand = ExpandTarget::None;
		break;

		case ImageProcessingStateMachine::DefiningCrop:
		enableCropping = true;
		expand = ExpandTarget::Cropping;
		break;

		case ImageProcessingStateMachine::ApplyingCrop:
		case ImageProcessingStateMachine::ApplyingRotation:
		case ImageProcessingStateMachine::ComputingThreshold:
		case ImageProcessingStateMachine::Segmenting:
		case ImageProcessingStateMachine::SavingSegment:
		// Long-running workers: disable UI
		expand = ExpandTarget::None;
		break;

		case ImageProcessingStateMachine::PlacingFiducials:
		enableFiducials = true;
		expand = ExpandTarget::Fiducials;
		break;

		case ImageProcessingStateMachine::InteractiveRotation:
		enableRotation = true;
		expand = ExpandTarget::Rotation;
		break;

		default:
		// conservative fallback: disable everything
		expand = ExpandTarget::None;
		break;
	}

	// Apply enable/disable using the public helpers (keeps encapsulation)
	setCroppingEnabled(enableCropping);
	setRotationEnabled(enableRotation);
	setSegmentationEnabled(enableSegmentation);
	setFiducialsEnabled(enableFiducials);
}

void WorkflowPanelWidget::setWindowLevelController(WindowLevelController* controller)
{
	// No-op if same controller already installed
	if (m_windowLevelController == controller) return;

	// If we previously had a controller, disconnect forwarding and remove it from appearance area.
	if (m_windowLevelController) {
		disconnect(m_windowLevelController, nullptr, this, nullptr);
		if (m_customAppearanceWidget && m_customAppearanceWidget.data() == m_windowLevelController) {
			m_customAppearanceWidget->setParent(nullptr);
			m_customAppearanceWidget.clear();
		}
	}

	m_windowLevelController = nullptr;

	if (!controller) return;

	// Ensure the controller is parented to this panel (so panel owns it) if caller didn't already parent it.
	if (!controller->parent()) {
		controller->setParent(this);
	}

	// Insert into appearance area (will reparent as needed)
	insertAppearanceWidget(controller);

	// Remember pointer and forward committed signals
	m_windowLevelController = controller;
	m_customAppearanceWidget = controller;

	connect(m_windowLevelController, &WindowLevelController::windowLevelCommitted,
			this, &WorkflowPanelWidget::windowLevelAdjusted, Qt::UniqueConnection);
}

// New: let panel own forwarding to LightboxWidget for real-time cropping
void WorkflowPanelWidget::setLightboxWidget(LightboxWidget* lightbox)
{
	// no-op if identical
	if (m_lightbox == lightbox) return;

	// disconnect previous if any
	if (m_lightbox) {
		// disconnect panel -> lightbox cropping forward
		disconnect(this, &WorkflowPanelWidget::croppingRegionChanged, m_lightbox, &LightboxWidget::setCroppingRegion);
		// disconnect Lightbox extents -> CropController if previously connected
		if (auto* crop = qobject_cast<CropController*>(m_customCroppingWidget.data())) {
			disconnect(m_lightbox, &LightboxWidget::imageExtentsChanged, crop, &CropController::setRangeSliders);
		}
		m_lightbox.clear();
	}

	if (!lightbox) return;

	// store and connect panel cropping -> lightbox
	m_lightbox = lightbox;
	connect(this, &WorkflowPanelWidget::croppingRegionChanged,
			m_lightbox, &LightboxWidget::setCroppingRegion, Qt::UniqueConnection);

	// Now connect LightboxWidget::imageExtentsChanged -> CropController::setRangeSliders,
	// so Lightbox is the mediator regardless of which child view produced the image.
	if (auto* crop = qobject_cast<CropController*>(m_customCroppingWidget.data())) {
		connect(m_lightbox, &LightboxWidget::imageExtentsChanged,
				crop, &CropController::setRangeSliders, Qt::UniqueConnection);
	}
}
